#!/bin/bash

# Define the titles and descriptions
categories=(
    "Supervised Learning|Training models with labeled data for classification and regression tasks."
    "Unsupervised Learning|Extracting hidden patterns from unlabeled data using clustering and dimensionality reduction."
    "Reinforcement Learning|Developing agents that learn optimal strategies through trial and error."
    "Neural Network Architectures|Exploring different deep learning models such as CNNs, RNNs, and Transformers."
    "Optimization Algorithms|Techniques like gradient descent, Adam, and RMSprop for training AI models efficiently."
    "Hyperparameter Tuning|Strategies like Grid Search, Random Search, and Bayesian Optimization for model performance improvement."
    "Model Deployment|Serving AI models with tools like TensorFlow Serving, TorchServe, and FastAPI."
    "Feature Engineering|Techniques for improving model performance by transforming raw data into informative features."
    "Dimensionality Reduction|Methods like PCA, t-SNE, and UMAP to reduce computational complexity while retaining important information."
    "Regularization Techniques|Preventing overfitting using L1/L2 regularization, dropout, and batch normalization."
    "Model Interpretability|Understanding AI decisions with SHAP, LIME, and feature importance analysis."
    "AutoML Frameworks|Automating model selection and hyperparameter tuning with libraries like AutoKeras and H2O.ai."
    "Bayesian Methods in AI|Probabilistic models and inference techniques for robust decision-making."
    "Sequence Modeling|Handling time-series and NLP tasks using architectures like LSTMs and Transformers."
    "Scalability in AI|Efficient AI training on large datasets using distributed computing and parallel processing."
    "Graph Neural Networks|Leveraging graph structures for applications in recommendation systems and fraud detection."
    "Self-Supervised Learning|Leveraging unlabeled data to pre-train AI models for better generalization."
    "AI Model Compression|Reducing model size and inference time with quantization, pruning, and knowledge distillation."
    "Federated Learning|Training AI models across decentralized data sources while preserving privacy."
    "Edge AI|Deploying AI models on low-power edge devices for real-time inference."
    "Few-Shot Learning|Improving model generalization with minimal training data."
    "Transfer Learning|Reusing pre-trained models to accelerate AI development."
    "Neuro-Symbolic AI|Combining neural networks with rule-based symbolic reasoning."
    "Multi-Agent Systems|Designing AI systems that collaborate and compete in dynamic environments."
    "Evolutionary Algorithms|Optimizing AI models using techniques inspired by natural selection."
    "Contrastive Learning|Enhancing representation learning through contrastive techniques."
    "Meta-Learning|Teaching AI to learn how to learn."
    "Zero-Shot Learning|Developing models that can recognize novel categories without prior training."
    "Graph-Based Learning|Using graph structures to improve AI model performance."
    "Explainable AI (XAI)|Creating interpretable AI models that build user trust."
    "Data Augmentation Techniques|Enhancing datasets with synthetic data for better model performance."
    "Adversarial Learning|Training models to be robust against adversarial attacks."
    "Self-Learning AI|Developing AI systems that improve their own learning process."
    "Tokenization in NLP|Breaking down text data into meaningful units for processing."
    "Quantum Machine Learning|Integrating quantum computing with AI for speed and efficiency."
    "Causal Inference in AI|Understanding cause-and-effect relationships in data-driven models."
    "Optimization in Reinforcement Learning|Improving policy learning and efficiency."
    "AI in Embedded Systems|Bringing AI capabilities to IoT and microcontrollers."
    "Deep Reinforcement Learning|Using deep neural networks to enhance RL decision-making."
    "Multimodal Learning|Combining multiple data sources (text, image, audio) for AI training."
    "Dynamic Graph Networks|Analyzing evolving graph-structured data using AI."
    "AI in Drug Discovery|Accelerating pharmaceutical research with machine learning."
    "Generative Adversarial Networks (GANs)|Synthesizing new data samples using adversarial training."
    "Bayesian Deep Learning|Adding uncertainty estimation to deep learning models."
    "Neural Architecture Search|Automatically designing AI model architectures."
    "Cross-Lingual NLP|Building AI models that understand multiple languages."
    "AI for Time Series Forecasting|Developing predictive models for temporal data."
    "Large Language Models (LLMs)|Exploring models like GPT and BERT for text processing."
    "AI in Scientific Computing|Using AI to accelerate research in physics, chemistry, and engineering."
)

# Create the markdown files
for category in "${categories[@]}"; do
    IFS='|' read -r title description <<< "$category"
    filename=$(echo "$title" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
    
    echo "---" > "${filename}.md"
    echo "title: '$title'" >> "${filename}.md"
    echo "description: '$description'" >> "${filename}.md"
    echo "---" >> "${filename}.md"
    
    echo "Created: ${filename}.md"
done
